### ISSUE TITLE
GUI buttons differ from window to window

### ISSUE THREAD

**Issue by Skypr** [NikolaiLMS/PSE-Wahlverfahren-Implementierung#12]
Bei den editoren bestehen unterschiede in der Reihenfolge der Knöpfe. wie sie angeordnet sind. Hier eine Auflistung aller Menüleisten (von links nach rechts)

- Parametereditor      ordner, speichern, speichern unter, Spezialknöpfe
- Eigenschaftenliste:   neu, ordner, speichern, speichern unter, rückgängig
- Eigenschaftenedior: neu, rückgängig, vorwärts, speichern, speichern unter, ordner, kopieren, auschschneiden, einfügen
- C-Editor: neu, speichern, speichern unter, ordner, rückgängig, vorwärts, kopieren, auschschneiden, einfügen

Meiner Meinung nach sollten wir uns auf ein einheitliches system einigen, sodass die betroffenden Fenster dann geändert werden können.

**Comment by NeilCorH** [comment]
Ich würde folgende Reihenfolge vorschlagen:
Neu, Öffnen, Speichern, Speichern Unter, Rückgängig, Wiederherstellen und dann Spezialfunktionen.

**Comment by justin-hecht** [comment]
Bin dafür, entspricht am meisten der gängigen Praxis.

**Comment by Skypr** [comment]
Ja, denke ich auch

**Comment by bigolol** [comment]
it is....done
