### ISSUE TITLE
Voters give candidates the same pos for preference voting

### ISSUE THREAD

**Issue by bigolol** [NikolaiLMS/PSE-Wahlverfahren-Implementierung#14]
I tried a very simple voting method which simply returned 0. Then I used ELECT1 != ELECT2 as a postprop. In the counter example, all voters had placed every candidate at spot 0.

**Comment by Skypr** [comment]
I tried it, but for me all results seem valid

**Comment by NeilCorH** [comment]
I can recreate the problem. I'm now trying to fix it

**Comment by NeilCorH** [comment]
fixed with 1.4.07
The Bug was happening because of a wrong code from me and because of the use of "magic strings" in the ElectionTemplateHolder class.
I will issue an improvement to use an enum for this an not strings.
