### ISSUE TITLE
Candidate Indexing in the Counterexample

### ISSUE THREAD

**Issue by NeilCorH** [NikolaiLMS/PSE-Wahlverfahren-Implementierung#15]
The indexes of the Candidates should start from 0 (not from 1). So they match the given votes (they start from 0 as well)
If the Candidate is the same number as C (the max number of Candidates) the counterexample should state "unentschieden" or something similar. Candidate C is NOT a Candidate but used as a 'not valid' statement.

**Comment by justin-hecht** [comment]
Fixed with commit 951631b

Which brings the version to 1.4.05
