### ISSUE TITLE
Possibility to extend and remove blocked code area

### ISSUE THREAD

**Issue by mi-ki** [NikolaiLMS/PSE-Wahlverfahren-Implementierung#16]
You can extend the gray and/or blocked area to further (previously non-blocked) parts of the code and hence also remove the previously blocked part.

Example:
1.) (Starting new voting method)
"unsigned int voting(unsigned int votes[V]) {
}"
2.) (Write "a" in first "legal" line)
"unsigned int voting(unsigned int votes[V]) { 
        a
} "
3.) (Press backspace at the first position of the line which includes the character "a")
"unsigned int voting(unsigned int votes[V]) {         a
} "
Now you cannot change or remove the character "a" again. It gets even stranger when you now revert your last action as then the gray area extends to the first inner line. If you now press enter at the end of the signature line, the gray area gets bigger (in this case by adding non-blocked lines).
Different variations of keystrokes can now lead to various unexpected behaviours (e.g., the "end" key may now even lead to an "IllegalArgumentException" in some swing component).

You might want to check for different hot keys inside your codearea and their effects on your blocked code area. I used the current (2017-03-09 23:58:24) standalone version from the svn repository on a linux (fedora) machine.

**Comment by bigolol** [comment]
c4499d82e8264a8879f1c59ccf50bfda2bbbd92d
