### ISSUE TITLE
CodeArea of the PreAndPostProperties BackspaceHandling

### ISSUE THREAD

**Issue by NeilCorH** [NikolaiLMS/PSE-Wahlverfahren-Implementierung#18]
How to recreate this bug:
Start the Program
Create a new Property
Select the Pre or PostpropertyArea
Press the backspace key.
The following Error (or similar) should appear:

Mär 11, 2017 3:18:18 PM edu.pse.beast.codearea.InputToCode.UserInsertToCode removeToTheLeft
SCHWERWIEGEND: null
javax.swing.text.BadLocationException: Invalid location

This shouldn't be an exception because many people will try to delete all of there input by just holding down the backspace key

Bug found on Version 1.4.05

**Comment by bigolol** [comment]
added an additional check when removing at pos 0. Also removed the standard logging to the console in commit ba94d919124838f5d87ddc13710a0b52735ea0ef
