### ISSUE TITLE
ParameterEditor Working-Icon is visible after TimeOut

### ISSUE THREAD

**Issue by NeilCorH** [NikolaiLMS/PSE-Wahlverfahren-Implementierung#19]
After a Timeout in the propertychecking occurs, the spinning Working Icon doesn't disappear. It stops "moving" but it will still be displayed.
The Icon stays even if you load another Project. 
Version 1.4.05

**Comment by NeilCorH** [comment]
This bug is harder to recreate than I thought.
It has something to do with creating a new ElectionDecription in the C-Editor window.
If the bug happens on a project and you save and reload it, it disappears if you reload it
![image_2017-03-12_23-43-54](https://cloud.githubusercontent.com/assets/23556636/23836796/3f38a02e-077e-11e7-81f0-3c8169ba8c80.png)

**Comment by NeilCorH** [comment]
Okay for me the following steps recreates the bug every time:
-Start the Program
-Open the CEditor
-Make a new ElectionDescription with the type **preference**. name it pref.
-add "return 0;" in the votingmethod of your new ElectionDescription.
-Open the PropertyList
-Create a new Property
-PreProperty "VOTES1 == VOTES2;"
-PostProperty "ELECT1 != ELECT2;"
-Select the Property you created for testing in the PropertyList.
-Run the test.
Version 1.4.08 on Windows 10.
The text is the same as in the shared picture above.
The actual tests takes about 2 seconds if I set the timeout to anything above 2 seconds.

**Comment by Skypr** [comment]
I tried it on Version 1.4.11 on Windows and it doesn't happen for me.
Can you verify that it is still a problem?

**Comment by NeilCorH** [comment]
Yes. The Problem still occurs
But you have to set the timeout to 1 second (at least on my machine) to make it appear

**Comment by NeilCorH** [comment]
Okay. An update on this issue:
How I can recreate it:
-Start the program
-Open the CEditor
-Make a new Cfile. (preference, candidate, name it pref, as code just use return 0)
-Open the Propertylist. Just add an empty property(the property doesn't seem to matter) and select it for checking
-Start the check
The following appears
![image](https://cloud.githubusercontent.com/assets/23556636/24082812/c00f2aae-0ccb-11e7-960b-5c63e1e28d61.png)

The icon is not spinning (it's a gif so that is weird)
Focusing on the parametereditor doesn't make the icon disappear.
What does make it disappear is minimizing and opening it again.

Strangely I don't get the bug if a save the projectfile, reload it and run it again.

I don't know what needs to be done to fix this. But it is rather strange and most of all not that important

**Comment by NeilCorH** [comment]
fixed with 1.4.21
There now is a method that minimizes and normalizes the window, which solves the problem
