### ISSUE TITLE
Refactoring SaverLoader Classes

### ISSUE THREAD

**Issue by bigolol** [NikolaiLMS/PSE-Wahlverfahren-Implementierung#21]
I was thinking about refactoring the saverloader classes to all use a helper class which would
encapsulate the common format of the save strings. The helper class would also parse given save strings
and provide access to their content via key-value pairs. I feel this change is somewhat necessary since the current method of saving strings isn't foolproof since it relies on certain patterns not appearing in the strings which are saved, for example patterns such as </code>. The helper would instead use the length of a given string to save it, in the format <length content>. I have already implemented the helper class and used it in the electiondescriptionsaverloader, and it works really well, however it would require resaving all the projects we currently use for testing. I think this would be well worth it. What do you guys think

**Comment by NeilCorH** [comment]
sounds like a good change.
The projects and files that are made by us until now shouldn't be to complicated to remake

**Comment by bigolol** [comment]
It is done my master
