### ISSUE TITLE
testGetZeroTabsForLine() in CurlyBracesLineBeginningTabHandlerTest doesn't work correct under windows

### ISSUE THREAD

**Issue by NeilCorH** [NikolaiLMS/PSE-Wahlverfahren-Implementierung#31]
either the test doesn't run at all or it just doesn't run correctly in windows.
I added an Ignore to it.
The creator of the test should fix this

**Comment by bigolol** [comment]
20bb30f9a8a9303bd7627062103aed11ac55877e simply removed the test
