### ISSUE TITLE
Possible way to save some processing time

### ISSUE THREAD

**Issue by Skypr** [NikolaiLMS/PSE-Wahlverfahren-Implementierung#32]
While profiling our program, I noticed that even when the checkers are running, the "ErrorFinder" and the "FindWordsConcurrently" keep on running and take up a lot of processing time. In my opinion we could just let them sleep while the checks are still running, to save that time and give cbmc possibly a bit more power.
![beast_processortime](https://cloud.githubusercontent.com/assets/7783618/23996378/6e924858-0a4d-11e7-942b-bb33c0f10652.png)

**Comment by bigolol** [comment]
implemented pause and resume for errorfinder in commit 3e513753f10af9402d6c81770859de16b3762c25
