### ISSUE TITLE
Can't save files in BooleanExpEditor and CElectionDescriptionEditor

### ISSUE THREAD

**Issue by NikolaiLMS** [NikolaiLMS/PSE-Wahlverfahren-Implementierung#38]
Since the refactoring you can't save files in BooleanExpEditor and CElectionDescriptionEditor even though the corresponding tests show no errors.
Output of the files doesn't look correct from first glance.

**Comment by bigolol** [comment]
fixed with commit d67b8147ad07819b2241751847ff2ad7e64cd144. When loading strings from a file, the a final \n is added to the savestring. This isn't accounted for by the loading algorithm which leads to a stringindexoutofbounds exception. This exception is now simply caught
