### ISSUE TITLE
Error in the Result Presentation

### ISSUE THREAD

**Issue by Skypr** [NikolaiLMS/PSE-Wahlverfahren-Implementierung#4]
If you have multiple Checker running at the same time (for example four) and the third finishes before the second, the Result of the third Checker is displayed in the Result slot of the second.
More general speaking: Results are presented in the order they have finished, not the order of the list that started the results. 

Possible fixes in my opinion:
1) just wait for all all results to be finished until you present (fix would just have to be made in the BeastCommunicator) (bad fix imo, because no status updates for the user)

2) traverse the loop that checks if the results are presentable with a foor loop, and give the current index variable of the loop to the presenter, so it knows in which order the results have to be presented

3) let the results have an index on their own that they get assigned during their creation, so the presenter can conclude which result he has to present where.

**Comment by Skypr** [comment]
Wenn die Klausurenpause vorbei ist müssen wir drei uns absprechen, welche Lösung uns als Gruppe am sinnvollsten erscheint

**Comment by justin-hecht** [comment]
IMHO wäre es das beste, wenn die Resultobjekte die jeweilige PostAndPrePropertiesDescription beinhalten würden. Dann ist die Zuordnung zu den Objekten am einfachsten. 
Das ist im Grunde Option 3. Aber ich will auch nicht ner Entscheidung vorgreifen.

**Comment by Skypr** [comment]
Ok, ich habe nun folgenden Vorschlag. Der BeastCommunicator weiß ja eigentlich schon den Index des Results. 

Aus diesem Grund schlage ich vor, dass Jonas aus dem Iterator eine normale forschleife macht (der performance unterschied wird minimal sein). Dann löschen wir nicht mehr die Objekte aus der Result liste, sondern
a) wir speichern einfach, dass wir diesen index schon präsentiert haben (einfach eine boolean liste von gleicher länge wie die resultliste)

b) ich füge eine Methode in das ResultInterface ein (wäre eine Änderung an einem SEHR hohem Interface), worin gespeichert werden kann, ob das Objekt schon presented wurde

c) wir geben alle objekte sofort zu justin, er ordnet sie alle zu, und der BeastCOmmunicator ruft immer nur eine Funktion (z.B: "checkResults()") auf, die dann im hintergrund alle result objekte durchgeht, und nur true zurück liefert, wenn alle objekte gefunden wurden.

**Comment by Skypr** [comment]
fixed the bug with the merge commit b7089fb6f23f47262f7dedf351e1a8ab85517030
