### ISSUE TITLE
Try to enable "User-includes"

### ISSUE THREAD

**Issue by Skypr** [NikolaiLMS/PSE-Wahlverfahren-Implementierung#9]
Try to allow the user to include more libraries into their code.

**Comment by NeilCorH** [comment]
I got a idea for a solution and am working on it.

**Comment by NeilCorH** [comment]
See the new branch userincludes.
Errorchecking or slight sanitychecking of the includes is still to be done

**Comment by NeilCorH** [comment]
UserIncludes were working fine allready. Well that was a waste of time...

**Comment by Skypr** [comment]
While normal includes that are standart c worked, there was no check, if they were correct, and also the user couldn't write own files to include

**Comment by Skypr** [comment]
Fixed this issue and enabled user written includes for windows and linux. Last commit that did this was 216f24babee7e79fb011c469fa6ec47404d71432
